Make testcase JDK/JRE independent
If JAVA_HOME is set to a JRE, no NoClassDefFoundError is reported but 
only a localized message saying that the main class was not found.